package frc.robot.subsystems;

import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;

import choreo.Choreo.TrajectoryLogger;
import choreo.auto.AutoFactory;
import choreo.trajectory.SwerveSample;
import dev.doglog.DogLog;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.units.Units;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.Current;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import frc.robot.constants.FieldConstants;
import frc.robot.constants.Settings;
import frc.robot.constants.FieldConstants.Locations;
import frc.robot.constants.Settings.kAutoAlign;
import frc.robot.constants.SystemConstants;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.util.AlignHelper;
import frc.robot.util.GeometryUtil;
import frc.robot.util.ProfiledController;

/**
 * Subsystem representing the Swerve Drivetrain.
 * Extends the generated TunerSwerveDrivetrain to add path following (Choreo) and vision integration.
 */
public class Swerve extends TunerSwerveDrivetrain implements Subsystem {
    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during field-centric path following */
    private final SwerveRequest.ApplyFieldSpeeds pathFieldSpeedsRequest = new SwerveRequest.ApplyFieldSpeeds()
    .withDriveRequestType(DriveRequestType.Velocity);
    private final PIDController pathXController = new PIDController(10, 0, 0);
    private final PIDController pathYController = new PIDController(10, 0, 0);
    private final PIDController pathThetaController = new PIDController(7, 0, 0);

    private final SwerveRequest.ApplyRobotSpeeds robotSpeedsRequest = new SwerveRequest.ApplyRobotSpeeds()
    .withDriveRequestType(DriveRequestType.Velocity);
    
    private static boolean aligned = false;


    private static final Angle kAimTolerance = Units.Degrees.of(5);

    private static final double DEADBAND = 0.1;
    private static final double TRIGGER_DEADBAND = 0.05;
    private static final double ANGLE_KP = 5.0;
    private static final double ANGLE_KD = 0;
    private static final double ANGLE_MAX_VELOCITY = 2.0;
    private static final double ANGLE_MAX_ACCELERATION = 5.0;

    private final StatusSignal<Current> mCurrentDraw1;
    private final StatusSignal<Current> mCurrentDraw2;
    private final StatusSignal<Current> mCurrentDraw3;
    private final StatusSignal<Current> mCurrentDraw4;

    private final StatusSignal<Angle> mAbsEnc1;
    private final StatusSignal<Angle> mAbsEnc2;
    private final StatusSignal<Angle> mAbsEnc3;
    private final StatusSignal<Angle> mAbsEnc4;


    private final ProfiledController translationController =
            new ProfiledController(
                kAutoAlign.ALIGN_PID,
                kAutoAlign.MAX_AUTO_ALIGN_VELOCITY_FAST.in(Units.MetersPerSecond),
                kAutoAlign.MAX_AUTO_ALIGN_ACCELERATION_FAST.in(Units.MetersPerSecondPerSecond)
            );

    private final ProfiledPIDController angleController = new ProfiledPIDController(
        ANGLE_KP,
         0.0,
        ANGLE_KD,
    new TrapezoidProfile.Constraints(ANGLE_MAX_VELOCITY, ANGLE_MAX_ACCELERATION)
    );

    /**
     * Creates a new Swerve subsystem.
     * Initializes the drivetrain with constants generated by Tuner X.
     */
    public Swerve() {
        super(
            TunerConstants.DrivetrainConstants, 
            0,
            VecBuilder.fill(0.1, 0.1, 0.1),
            VecBuilder.fill(0.1, 0.1, 0.1),
            TunerConstants.FrontLeft, 
            TunerConstants.FrontRight, 
            TunerConstants.BackLeft, 
            TunerConstants.BackRight
        );

      mCurrentDraw1 = getModule(0).getDriveMotor().getSupplyCurrent();
      mCurrentDraw2 = getModule(1).getDriveMotor().getSupplyCurrent();
      mCurrentDraw3 = getModule(2).getDriveMotor().getSupplyCurrent();
      mCurrentDraw4 = getModule(3).getDriveMotor().getSupplyCurrent();

      mAbsEnc1 = getModule(0).getEncoder().getAbsolutePosition();
      mAbsEnc2 = getModule(1).getEncoder().getAbsolutePosition();
      mAbsEnc3 = getModule(2).getEncoder().getAbsolutePosition();
      mAbsEnc4 = getModule(3).getEncoder().getAbsolutePosition();

      angleController.enableContinuousInput(-Math.PI, Math.PI);
    }

    /**
     * Creates a new auto factory for this drivetrain.
     *
     * @return AutoFactory for this drivetrain
     */
    public AutoFactory createAutoFactory() {
        return createAutoFactory((sample, isStart) -> {});
    }

    /**
     * Creates a new auto factory for this drivetrain with the given
     * trajectory logger.
     *
     * @param trajLogger Logger for the trajectory
     * @return AutoFactory for this drivetrain
     */
    public AutoFactory createAutoFactory(TrajectoryLogger<SwerveSample> trajLogger) {
        return new AutoFactory(
            () -> getState().Pose,
            this::resetPose,
            this::followPath,
            true,
            this,
            trajLogger
        );
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequestCommand(Supplier<SwerveRequest> requestSupplier) {
        return run(() -> this.setControl(requestSupplier.get()));
    }

    public void applyRequest(Supplier<SwerveRequest> requestSupplier) {
        this.setControl(requestSupplier.get());
    }

    public void stop() {
        this.setControl(new SwerveRequest.Idle());
    }



    /**
     * Follows the given field-centric path sample with PID.
     *
     * @param sample Sample along the path to follow
     */
    public void followPath(SwerveSample sample) {
        pathThetaController.enableContinuousInput(-Math.PI, Math.PI);

        var pose = getState().Pose;

        var targetSpeeds = sample.getChassisSpeeds();
        targetSpeeds.vxMetersPerSecond += pathXController.calculate(
            pose.getX(), sample.x
        );
        targetSpeeds.vyMetersPerSecond += pathYController.calculate(
            pose.getY(), sample.y
        );
        targetSpeeds.omegaRadiansPerSecond += pathThetaController.calculate(
            pose.getRotation().getRadians(), sample.heading
        );

        setControl(
            pathFieldSpeedsRequest.withSpeeds(targetSpeeds)
                .withWheelForceFeedforwardsX(sample.moduleForcesX())
                .withWheelForceFeedforwardsY(sample.moduleForcesY())
        );
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                if (!m_hasAppliedOperatorPerspective) {
                    seedFieldCentric();
                }
                m_hasAppliedOperatorPerspective = true;
            });
        }

        
        DogLog.log("DogLogSwerve/DistanceToHubMeters", getState().Pose.getTranslation().getDistance(FieldConstants.Locations.hubPosition()));
        DogLog.log("DogLogSwerve/Pose", getState().Pose);
        DogLog.log("DogLogSwerve/isAimed", isAimedAtHub());

        BaseStatusSignal.refreshAll(mCurrentDraw1, mCurrentDraw2, mCurrentDraw3, mCurrentDraw4, mAbsEnc1, mAbsEnc2, mAbsEnc3, mAbsEnc4);


        DogLog.log("DogLogSwerve/CurrentDraw1", mCurrentDraw1.getValueAsDouble());
        DogLog.log("DogLogSwerve/CurrentDraw2", mCurrentDraw2.getValueAsDouble());
        DogLog.log("DogLogSwerve/CurrentDraw3", mCurrentDraw3.getValueAsDouble());
        DogLog.log("DogLogSwerve/CurrentDraw4", mCurrentDraw4.getValueAsDouble());

        DogLog.log("DogLogSwerve/Swerve0AbsEncoderPos", mAbsEnc1.getValueAsDouble());
        DogLog.log("DogLogSwerve/Swerve1AbsEncoderPos", mAbsEnc2.getValueAsDouble());
        DogLog.log("DogLogSwerve/Swerve2AbsEncoderPos", mAbsEnc3.getValueAsDouble());
        DogLog.log("DogLogSwerve/Swerve3AbsEncoderPos", mAbsEnc4.getValueAsDouble());

    }

    public Distance hubDistInMeters() {
        return Units.Meters.of(getState().Pose.getTranslation().getDistance(FieldConstants.Locations.hubPosition()));
    }

    public boolean isAimedAtHub() {
        final Rotation2d targetHeading = getShooterDirectionToHub();
        
        // Get current heading in Blue Alliance perspective (standard field coordinates)
        final Rotation2d currentHeadingInBlueAlliancePerspective = this.getState().Pose.getRotation();
        
        // Convert to Operator Perspective to match the request's frame of reference
        final Rotation2d currentHeadingInOperatorPerspective = currentHeadingInBlueAlliancePerspective.rotateBy(this.getOperatorForwardDirection());
        
        return GeometryUtil.isNear(targetHeading, currentHeadingInOperatorPerspective, kAimTolerance);
    }

    public boolean isAimedAtVirtualTarget(Rotation2d virtualTargetAngle) {
    final Rotation2d currentHeading = getState().Pose.getRotation()
        .rotateBy(getOperatorForwardDirection());
    return GeometryUtil.isNear(virtualTargetAngle, currentHeading, kAimTolerance);
    }

    public Rotation2d getShooterDirectionToHub() {
        final Translation2d hubPosition = Locations.hubPosition();
        final Pose2d robotPose = this.getState().Pose;
        Pose2d launcherPosition = robotPose.transformBy(GeometryUtil.toTransform2d(SystemConstants.Flywheel.ROBOT_TO_SHOOTER_TRANSFORM));
        final Translation2d shooterPos = launcherPosition.getTranslation();

        
        // Calculate angle in standard field coordinates (Blue Alliance origin)
        final Rotation2d hubDirectionInBlueAlliancePerspective = hubPosition.minus(shooterPos).getAngle();
        
        // Adjust for the driver's perspective (Red vs Blue alliance)
        final Rotation2d hubDirectionInOperatorPerspective = hubDirectionInBlueAlliancePerspective.rotateBy(this.getOperatorForwardDirection());
        
        return hubDirectionInOperatorPerspective;
    }

    public boolean isAimedAtShuttle() {
        final Rotation2d targetHeading = getShooterDirectionToShuttle();
        
        // Get current heading in Blue Alliance perspective (standard field coordinates)
        final Rotation2d currentHeadingInBlueAlliancePerspective = this.getState().Pose.getRotation();
        
        // Convert to Operator Perspective to match the request's frame of reference
        final Rotation2d currentHeadingInOperatorPerspective = currentHeadingInBlueAlliancePerspective.rotateBy(this.getOperatorForwardDirection());
        
        return GeometryUtil.isNear(targetHeading, currentHeadingInOperatorPerspective, kAimTolerance);
    }

    public Rotation2d getShooterDirectionToShuttle() {
        final Pose2d robotPose = this.getState().Pose;
        Pose2d launcherPosition = robotPose.transformBy(GeometryUtil.toTransform2d(SystemConstants.Flywheel.ROBOT_TO_SHOOTER_TRANSFORM));
        final Translation2d shooterPos = launcherPosition.getTranslation();
        Translation2d closestShuttlingPos = FieldConstants.Locations.getClosestShuttlingPosition(getState().Pose).getTranslation();
        final Rotation2d hubDirectionInBlueAlliancePerspective = closestShuttlingPos.minus(shooterPos).getAngle();
        
        // Adjust for the driver's perspective (Red vs Blue alliance)
        final Rotation2d hubDirectionInOperatorPerspective = hubDirectionInBlueAlliancePerspective.rotateBy(this.getOperatorForwardDirection());
        
        return hubDirectionInOperatorPerspective;

    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }


    // Returns distance in meters
    public double getDistanceToHub() {
        final Translation2d hubPosition = FieldConstants.Locations.hubPosition();
        final Pose2d robotPose = this.getState().Pose;

        return robotPose.getTranslation().getDistance(hubPosition);
    }

    public double getDistance(Translation2d target) {
        final Pose2d robotpose = this.getState().Pose;
        return robotpose.getTranslation().getDistance(target);
    }

    public ChassisSpeeds getFieldRelativeSpeeds() {
        ChassisSpeeds speeds = getState().Speeds;
        Rotation2d rot = getState().Pose.getRotation();
        return ChassisSpeeds.fromRobotRelativeSpeeds(speeds, rot);
    }

    public Command finalClimbLineupCommand() {
        return Commands.sequence(
            this.applyRequestCommand(() -> robotSpeedsRequest.withSpeeds(
                new ChassisSpeeds(0, 
                Settings.ClimbLineupSettings.SIDELINEUP_VELOCITY, 
                0)
            )).withTimeout(Settings.ClimbLineupSettings.SIDEWAYS_LINEUP_TIMEOUT),
            this.applyRequestCommand(() -> robotSpeedsRequest.withSpeeds(
                new ChassisSpeeds(
                Settings.ClimbLineupSettings.FORWLINEUP_VELOCITY,
                0,
                0)
            )).withTimeout(Settings.ClimbLineupSettings.FORWARD_LINEUP_TIMEOUT)
            );
    }

    public Command pushIntoOutpostCmd() {
        return Commands.sequence(
            this.applyRequestCommand(
                () -> robotSpeedsRequest.withSpeeds(
                    new ChassisSpeeds(
                        Settings.OutpostLineupSettings.FORWLINEUP_VELOCITY,
                        0,
                        0
                    )
                )
            ).withTimeout(Settings.OutpostLineupSettings.FORWARD_LINEUP_TIMEOUT)
        );
    }

    public Command alignToPoint(Supplier<Pose2d> target) {
        return Commands.sequence(
            Commands.runOnce(() -> {
                // Reset speeds of the controller
                aligned = false;

                ChassisSpeeds speeds = getFieldRelativeSpeeds();

                translationController.reset(-Math.hypot(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond));
                angleController.reset(this.getState().Pose.getRotation().getRadians());
            }),
            Commands.run(() -> {
                // Update the contraints of the controller
                Pose2d robotPose = this.getState().Pose;
                Rotation2d rot = robotPose.getRotation();
                Pose2d targetPose = target.get();

                
                double xDiff = targetPose.getX() - robotPose.getX();
                double yDiff = targetPose.getY() - robotPose.getY();

                double totalDiff = Math.hypot(xDiff, yDiff);

                double speed = Math.abs(translationController.calculate(totalDiff, 0.0));
        
                double omega =
                angleController.calculate(
                    robotPose.getRotation().getRadians(), targetPose.getRotation().getRadians());
                                            
                // Trig cacl for converting back to field relative
                double speedX = speed * (xDiff / totalDiff);
                double speedY = speed * (yDiff / totalDiff);



                this.setControl(robotSpeedsRequest.withSpeeds(
                    ChassisSpeeds.fromFieldRelativeSpeeds(speedX, speedY, omega, rot)
                ));
                

                DogLog.log("AutoAlign/Target", targetPose);
                DogLog.log("AutoAlign/SpeedOutput", speed);
                DogLog.log("AutoAlign/OmegaOutput", omega);
                DogLog.log("AutoAlign/MaxVelo [m per s]", translationController.getMaxVelocity());
                DogLog.log("AutoAlign/MaxAccel [m per s^2]", translationController.getMaxAcceleration());
            }, this)
        ).until(() -> {
            Pose2d robotPose = this.getState().Pose;
            Pose2d targetPose = target.get();

            Angle difference = AlignHelper.rotationDifference(targetPose.getRotation(), robotPose.getRotation());

            Distance distance = Units.Meters.of(Math.hypot(robotPose.getX() - targetPose.getX(), robotPose.getY() - targetPose.getY()));

            ChassisSpeeds speeds = this.getState().Speeds;
            LinearVelocity robotSpeed = Units.MetersPerSecond.of(Math.hypot(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond));

            DogLog.log("AutoAlign/Distance To Alignment [cm]", distance.in(Units.Centimeters));
            DogLog.log("AutoAlign/Angle To Alignment [degrees]", difference.in(Units.Degrees));
            DogLog.log("AutoAlign/Velocity [m per s]", robotSpeed.in(Units.MetersPerSecond));
        
            if (DriverStation.isAutonomous())
                return
                    distance.lte(kAutoAlign.TRANSLATION_TOLERANCE) &&
                    difference.lte(kAutoAlign.ROTATION_TOLERANCE) &&
                    robotSpeed.lte(kAutoAlign.VELOCITY_TOLERANCE);
            else
                return
                    distance.lte(kAutoAlign.TRANSLATION_TOLERANCE) &&
                    difference.lte(kAutoAlign.ROTATION_TOLERANCE) &&
                    robotSpeed.lte(kAutoAlign.AUTO_VELOCITY_TOLERANCE);
        }
    ).andThen(
        Commands.runOnce(() -> {
            this.stop();
            aligned = true;
        }, this)
    );
    }


     /**
     * Seeds the Kalman Filter with a reasonable initial pose estimate based on the driver's perspective.
     * This can help correct for any significant odometry drift that may have occurred since the last time the operator perspective was applied.
     */
}