
package frc.robot.util;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj ShootPreloaded = new ChoreoTraj(
	    "ShootPreloaded",
	    OptionalInt.empty(),
	    1.33637,
	    new Pose2d(3.554, 0.897, Rotation2d.fromRadians(0)),
	    new Pose2d(2.151, 2.631, Rotation2d.fromRadians(0.588))
	);
	public static final ChoreoTraj LeftCenterBeelineNoSweep = new ChoreoTraj(
	    "LeftCenterBeelineNoSweep",
	    OptionalInt.empty(),
	    7.89758,
	    new Pose2d(3.35, 5.5, Rotation2d.fromRadians(-0.785)),
	    new Pose2d(2.896, 5.382, Rotation2d.fromRadians(-0.76))
	);
	public static final ChoreoTraj LeftCenterBeelineNoSweep$0 = new ChoreoTraj(
	    "LeftCenterBeelineNoSweep",
	    OptionalInt.of(0),
	    1.09145,
	    new Pose2d(3.35, 5.5, Rotation2d.fromRadians(-0.785)),
	    new Pose2d(5.863, 5.5, Rotation2d.fromRadians(-0.785))
	);
	public static final ChoreoTraj LeftCenterBeelineNoSweep$1 = new ChoreoTraj(
	    "LeftCenterBeelineNoSweep",
	    OptionalInt.of(1),
	    4.63965,
	    new Pose2d(5.863, 5.5, Rotation2d.fromRadians(-0.785)),
	    new Pose2d(6.622, 5.392, Rotation2d.fromRadians(2.336))
	);
	public static final ChoreoTraj LeftCenterBeelineNoSweep$2 = new ChoreoTraj(
	    "LeftCenterBeelineNoSweep",
	    OptionalInt.of(2),
	    2.16648,
	    new Pose2d(6.622, 5.392, Rotation2d.fromRadians(2.336)),
	    new Pose2d(2.896, 5.382, Rotation2d.fromRadians(-0.76))
	);
	public static final ChoreoTraj LeftCenterBeelineSweep = new ChoreoTraj(
	    "LeftCenterBeelineSweep",
	    OptionalInt.empty(),
	    8.98527,
	    new Pose2d(3.35, 5.5, Rotation2d.fromRadians(0.785)),
	    new Pose2d(2.697, 5.5, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj LeftCenterBeelineSweep$0 = new ChoreoTraj(
	    "LeftCenterBeelineSweep",
	    OptionalInt.of(0),
	    1.09145,
	    new Pose2d(3.35, 5.5, Rotation2d.fromRadians(0.785)),
	    new Pose2d(5.863, 5.5, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj LeftCenterBeelineSweep$1 = new ChoreoTraj(
	    "LeftCenterBeelineSweep",
	    OptionalInt.of(1),
	    6.59349,
	    new Pose2d(5.863, 5.5, Rotation2d.fromRadians(0.785)),
	    new Pose2d(6.263, 5.5, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj LeftCenterBeelineSweep$2 = new ChoreoTraj(
	    "LeftCenterBeelineSweep",
	    OptionalInt.of(2),
	    1.3003299999999998,
	    new Pose2d(6.263, 5.5, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(2.697, 5.5, Rotation2d.fromRadians(-2.356))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("ShootPreloaded", ShootPreloaded),
		Map.entry("LeftCenterBeelineNoSweep", LeftCenterBeelineNoSweep),
		Map.entry("LeftCenterBeelineNoSweep$0", LeftCenterBeelineNoSweep$0),
		Map.entry("LeftCenterBeelineNoSweep$1", LeftCenterBeelineNoSweep$1),
		Map.entry("LeftCenterBeelineNoSweep$2", LeftCenterBeelineNoSweep$2),
		Map.entry("LeftCenterBeelineSweep", LeftCenterBeelineSweep),
		Map.entry("LeftCenterBeelineSweep$0", LeftCenterBeelineSweep$0),
		Map.entry("LeftCenterBeelineSweep$1", LeftCenterBeelineSweep$1),
		Map.entry("LeftCenterBeelineSweep$2", LeftCenterBeelineSweep$2)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
