
package frc.robot.util;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj B_BEELINE = new ChoreoTraj(
	    "B_BEELINE",
	    OptionalInt.empty(),
	    8.66331,
	    new Pose2d(3.544, 2.42, Rotation2d.fromRadians(0)),
	    new Pose2d(2.2, 2.63, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj B_BEELINE$0 = new ChoreoTraj(
	    "B_BEELINE",
	    OptionalInt.of(0),
	    1.22817,
	    new Pose2d(3.544, 2.42, Rotation2d.fromRadians(0)),
	    new Pose2d(6.72, 2.48, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj B_BEELINE$1 = new ChoreoTraj(
	    "B_BEELINE",
	    OptionalInt.of(1),
	    1.2854200000000002,
	    new Pose2d(6.72, 2.48, Rotation2d.fromRadians(0)),
	    new Pose2d(7.81, 0.9, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj B_BEELINE$2 = new ChoreoTraj(
	    "B_BEELINE",
	    OptionalInt.of(2),
	    3.9113899999999995,
	    new Pose2d(7.81, 0.9, Rotation2d.fromRadians(1.571)),
	    new Pose2d(6.172, 2.63, Rotation2d.fromRadians(0.06))
	);
	public static final ChoreoTraj B_BEELINE$3 = new ChoreoTraj(
	    "B_BEELINE",
	    OptionalInt.of(3),
	    2.2383299999999995,
	    new Pose2d(6.172, 2.63, Rotation2d.fromRadians(0.06)),
	    new Pose2d(2.2, 2.63, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj C_BEELINE = new ChoreoTraj(
	    "C_BEELINE",
	    OptionalInt.empty(),
	    8.95469,
	    new Pose2d(3.538, 5.596, Rotation2d.fromRadians(0)),
	    new Pose2d(2, 5.35, Rotation2d.fromRadians(-0.785))
	);
	public static final ChoreoTraj C_BEELINE$0 = new ChoreoTraj(
	    "C_BEELINE",
	    OptionalInt.of(0),
	    1.8607,
	    new Pose2d(3.538, 5.596, Rotation2d.fromRadians(0)),
	    new Pose2d(6.782, 5.628, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj C_BEELINE$1 = new ChoreoTraj(
	    "C_BEELINE",
	    OptionalInt.of(1),
	    1.2444600000000001,
	    new Pose2d(6.782, 5.628, Rotation2d.fromRadians(0)),
	    new Pose2d(7.81, 7.096, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj C_BEELINE$2 = new ChoreoTraj(
	    "C_BEELINE",
	    OptionalInt.of(2),
	    3.46473,
	    new Pose2d(7.81, 7.096, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(6.359, 5.35, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj C_BEELINE$3 = new ChoreoTraj(
	    "C_BEELINE",
	    OptionalInt.of(3),
	    2.3847999999999994,
	    new Pose2d(6.359, 5.35, Rotation2d.fromRadians(0)),
	    new Pose2d(2, 5.35, Rotation2d.fromRadians(-0.785))
	);
	public static final ChoreoTraj C_DEPOT_ONETIME = new ChoreoTraj(
	    "C_DEPOT_ONETIME",
	    OptionalInt.empty(),
	    4.72357,
	    new Pose2d(3.538, 5.571, Rotation2d.fromRadians(0)),
	    new Pose2d(2, 4.949, Rotation2d.fromRadians(-0.606))
	);
	public static final ChoreoTraj C_DEPOT_ONETIME$0 = new ChoreoTraj(
	    "C_DEPOT_ONETIME",
	    OptionalInt.of(0),
	    0.90549,
	    new Pose2d(3.538, 5.571, Rotation2d.fromRadians(0)),
	    new Pose2d(2.038, 6.091, Rotation2d.fromRadians(-0.741))
	);
	public static final ChoreoTraj C_DEPOT_ONETIME$1 = new ChoreoTraj(
	    "C_DEPOT_ONETIME",
	    OptionalInt.of(1),
	    3.4367000000000005,
	    new Pose2d(2.038, 6.091, Rotation2d.fromRadians(-0.741)),
	    new Pose2d(2, 4.944, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj C_DEPOT_ONETIME$2 = new ChoreoTraj(
	    "C_DEPOT_ONETIME",
	    OptionalInt.of(2),
	    0.38137999999999916,
	    new Pose2d(2, 4.944, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2, 4.949, Rotation2d.fromRadians(-0.606))
	);
	public static final ChoreoTraj X_CLIMB_NEARD = new ChoreoTraj(
	    "X_CLIMB_NEARD",
	    OptionalInt.empty(),
	    3.17,
	    new Pose2d(3.457, 3.961, Rotation2d.fromRadians(0)),
	    new Pose2d(1.228, 5.071, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj X_CLIMB_NEARD$0 = new ChoreoTraj(
	    "X_CLIMB_NEARD",
	    OptionalInt.of(0),
	    0.75366,
	    new Pose2d(3.457, 3.961, Rotation2d.fromRadians(0)),
	    new Pose2d(2.596, 3.969, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj X_CLIMB_NEARD$1 = new ChoreoTraj(
	    "X_CLIMB_NEARD",
	    OptionalInt.of(1),
	    2.41634,
	    new Pose2d(2.596, 3.969, Rotation2d.fromRadians(0)),
	    new Pose2d(1.228, 5.071, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj X_DEPOT = new ChoreoTraj(
	    "X_DEPOT",
	    OptionalInt.empty(),
	    8.70464,
	    new Pose2d(3.545, 4.019, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.209, 5.156, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj X_DEPOT$0 = new ChoreoTraj(
	    "X_DEPOT",
	    OptionalInt.of(0),
	    1.77114,
	    new Pose2d(3.545, 4.019, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.073, 5.895, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj X_DEPOT$1 = new ChoreoTraj(
	    "X_DEPOT",
	    OptionalInt.of(1),
	    3.97394,
	    new Pose2d(2.073, 5.895, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.761, 6.405, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj X_DEPOT$2 = new ChoreoTraj(
	    "X_DEPOT",
	    OptionalInt.of(2),
	    1.4764499999999998,
	    new Pose2d(1.761, 6.405, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.209, 5.156, Rotation2d.fromRadians(-0.343))
	);
	public static final ChoreoTraj X_DEPOT$3 = new ChoreoTraj(
	    "X_DEPOT",
	    OptionalInt.of(3),
	    1.48311,
	    new Pose2d(1.209, 5.156, Rotation2d.fromRadians(-0.343)),
	    new Pose2d(1.209, 5.156, Rotation2d.fromRadians(3.142))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("B_BEELINE", B_BEELINE),
		Map.entry("B_BEELINE$0", B_BEELINE$0),
		Map.entry("B_BEELINE$1", B_BEELINE$1),
		Map.entry("B_BEELINE$2", B_BEELINE$2),
		Map.entry("B_BEELINE$3", B_BEELINE$3),
		Map.entry("C_BEELINE", C_BEELINE),
		Map.entry("C_BEELINE$0", C_BEELINE$0),
		Map.entry("C_BEELINE$1", C_BEELINE$1),
		Map.entry("C_BEELINE$2", C_BEELINE$2),
		Map.entry("C_BEELINE$3", C_BEELINE$3),
		Map.entry("C_DEPOT_ONETIME", C_DEPOT_ONETIME),
		Map.entry("C_DEPOT_ONETIME$0", C_DEPOT_ONETIME$0),
		Map.entry("C_DEPOT_ONETIME$1", C_DEPOT_ONETIME$1),
		Map.entry("C_DEPOT_ONETIME$2", C_DEPOT_ONETIME$2),
		Map.entry("X_CLIMB_NEARD", X_CLIMB_NEARD),
		Map.entry("X_CLIMB_NEARD$0", X_CLIMB_NEARD$0),
		Map.entry("X_CLIMB_NEARD$1", X_CLIMB_NEARD$1),
		Map.entry("X_DEPOT", X_DEPOT),
		Map.entry("X_DEPOT$0", X_DEPOT$0),
		Map.entry("X_DEPOT$1", X_DEPOT$1),
		Map.entry("X_DEPOT$2", X_DEPOT$2),
		Map.entry("X_DEPOT$3", X_DEPOT$3)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
